var dummyBook = [
  {
    'id': 1,
    'name': 'Pemrograman C++',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/cplus.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 2,
    'name': 'PHP dan MySQL',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/mysql.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 3,
    'name': 'Python',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/python1.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 4,
    'name': 'Pemrograman PHP5',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/php5.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 5,
    'name': 'Economy',
    'description': 'Pembelajaran ekonomi.',
    'image': 'assets/global/img/buku/economy.png',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['bisnis', 'ekonomi'],
  },
  {
    'id': 6,
    'name': 'Management',
    'description': 'Pembelajaran management.',
    'image': 'assets/global/img/buku/Management.png',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['management', 'bisnis'],
  },
  {
    'id': 7,
    'name': 'Pemrograman Phyton',
    'description': 'Pembelajaran pemrograman python.',
    'image': 'assets/global/img/buku/python2.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'python'],
  },
  {
    'id': 8,
    'name': 'TOEFL',
    'description': 'Pembelajaran TOEFL.',
    'image': 'assets/global/img/buku/toefl.png',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['toefl', 'TOEFL', 'Bahasa Inggris'],
  },
  {
    'id': 9,
    'name': 'Start Up',
    'description': 'Pembelajaran business start up.',
    'image': 'assets/global/img/buku/startup.png',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['bisnis', 'business'],
  },
];
