var dummyBook = [
  {
    'id': 1,
    'name': 'Pemrograman C++',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/cplus.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 2,
    'name': 'PHP dan MySQL',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/cplus.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 3,
    'name': 'Python',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/cplus.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
  {
    'id': 4,
    'name': 'Pemrograman PHP5',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'image': 'assets/global/img/buku/cplus.jpg',
    'author': 'Dr. Alba',
    'publisher': 'DSDI',
    'year': 2009,
    'location': 'Perpustakaan Pusat UGM',
    'passions': ['programming', 'data-analis'],
  },
];
