var dummyCourse = [
  {
    'id': 1,
    'name': 'Algoritma dan Struktur Data',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'lecturer': 'Dr. Alba',
    'schedule': 'Kamis, 13.00',
    'location': 'DSDI',
    'score': 'A',
    'passions': ['programming', 'data-analis'],
    'weight': {
      'web-programmer': 0,
      'security-engineer': 0,
      'bussiness-analyst': 0,
      'system-analyst': 1,
      'designer': 0,
    },
  },
  {
    'id': 2,
    'name': 'Teknik Pengolahan Citra',
    'description': 'Pembelajaran citra dan pengolahannya.',
    'lecturer': 'Dr. Alba',
    'schedule': 'Kamis, 13.00',
    'location': 'DSDI',
    'score': 'B',
    'passions': ['programming', 'data-analis'],
    'weight': {
      'web-programmer': 0,
      'security-engineer': 0,
      'bussiness-analyst': 0,
      'system-analyst': 0,
      'designer': 1,
    },
  },
  {
    'id': 3,
    'name': 'Topik Khusus Teknologi Informasi',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'lecturer': 'Dr. Alba',
    'schedule': 'Kamis, 13.00',
    'location': 'DSDI',
    'score': 'A',
    'passions': ['programming', 'data-analis'],
    'weight': {
      'web-programmer': 0,
      'security-engineer': 0,
      'bussiness-analyst': 0,
      'system-analyst': 1,
      'designer': 0,
    },
  },
  {
    'id': 4,
    'name': 'Pemrograman Jaringan dan Web',
    'description': 'Pembelajaran algoritma dan struktur data.',
    'lecturer': 'Dr. Alba',
    'schedule': 'Kamis, 13.00',
    'location': 'DSDI',
    'score': 'C',
    'passions': ['programming', 'data-analis'],
    'weight': {
      'web-programmer': 1,
      'security-engineer': 0,
      'bussiness-analyst': 0,
      'system-analyst': 0,
      'designer': 0,
    },
  },
];
