var dummyJob = [
  {
    'id': 1,
    'position': 'Ahli Struktur Data',
    'description': 'Optimasi struktur data dan maintenance.',
    'requirement': 'Mampu mengoptimasi struktur data dengan luar biasa.',
    'company': 'Gaagle Inc.',
    'profesion': 'system-analyst',
  },
  {
    'id': 2,
    'position': 'Data Analis',
    'description': 'Optimasi struktur data dan maintenance.',
    'requirement': 'Memahami minimal 3 teknik analisis data.',
    'company': 'SelaStack Indonesia',
    'profesion': 'system-analyst',
  },
  {
    'id': 3,
    'position': 'Programmer Frontend',
    'description': 'Mendesain tampilan.',
    'requirement': 'Mampu mengoptimasi struktur data dengan luar biasa.',
    'company': 'PT. TakaBugas',
    'profesion': 'designer',
  },
  {
    'id': 4,
    'position': 'Ahli Keamanan Jaringan',
    'description': 'Mencegah serangan DDoS internasional.',
    'requirement': 'Mengetahui cara mendekripsi SSH.',
    'company': 'Gaagle Inc.',
    'profesion': 'security-engineer',
  },
  {
    'id': 5,
    'position': 'Programmer Backend',
    'description': 'Melakukan maintenance dan refactoring.',
    'requirement': 'Menguasai git, PHP, MySQL, mudah belajar.',
    'company': 'PT. TakaBugas',
    'profesion': 'designer',
  },
  {
    'id': 6,
    'position': 'Bussiness Strategist',
    'description': 'Melakukan perencanaan bisnis beserta analisisnya.',
    'requirement': 'Menguasai teknik.',
    'company': 'Gaagle Inc.',
    'profesion': 'bussiness-analyst',
  },
];
